seed_everything: 42
model:
    class_path: gLM.models.gLM2
    init_args:
        model: 
            class_path: gLM.models.CategoricalJacobian
            init_args:
                model_path: "./mint/mint/model/mint.ckpt"
                config_path: "./mint/mint/model/esm2_t33_650M_UR50D.json"
                fast: true
                matrix_path: ./outputs/categorical_jacobians/mint_cosine/
                distance: "cosine"
                sep_chains: true
data:
    class_path: gLM.dataloader.SequencePairCJDataModule
    init_args:
        fasta_file: ./data/ModAC/sequences.fasta
        data_folder: ./data/ModAC
        batch_size: 4096
        positive_only: false
        num_workers: 4
        num_samples: null
        concat_type: "mint"
optimizer:
    class_path: torch.optim.Adam
    init_args:
        lr: 0.001
        weight_decay: 0.0001
trainer:
    max_epochs: 1
    deterministic: true
    logger:
        class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            save_dir: 'logs'
            offline: true
            project: gLM_PPI_XAI
            name: 'ModAC-MINT'
            log_model: false
            prefix: 'sep-cosine-fastCJ'
    enable_checkpointing: true
    callbacks:
      - class_path: gLM.callbacks.SetupWandB 
      - class_path: gLM.callbacks.OutputLoggingCallback
        init_args:
            log_every_n_steps: 1
      - class_path: gLM.callbacks.LogClassificationMetrics
        init_args:
          class_names:
          - 'Negative'
          - 'Positive'
          y_pred_key: predictions
          y_pred_lab_key: predicted_label
          y_true_lab_key: label
          make_one_hot: true
          invert_probabilities: false
          make_correct_dim: true
          metrics_to_plot:
            - confusion_matrix
            - class_proportions
            - calibration_curves
            - classification_report
            - mcc
            - roc_auc
            - pr_auc
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
            dirpath: logs/ModAC/checkpoints/optimized/
            filename: model-{epoch}
            monitor: validate/loss
            mode: min
            save_last: true
            save_top_k: 1
