seed_everything: 42
model:
    class_path: gLM.models.gLM2
    init_args:
        model: 
            class_path: gLM.models.CategoricalJacobian
            init_args:
                model_path: "./gLM2_650M/"
                config_path: ""
                fast: true
                matrix_path: ./outputs/categorical_jacobians/glm2_cosine_post250521/
                distance: "cosine"
                n: 3
data:
    class_path: gLM.dataloader.SequencePairCJDataModule
    init_args:
        fasta_file: ./data/TASmania/mycobacterium_tuberculosis/sequences.fasta
        data_folder: ./data/TASmania/mycobacterium_tuberculosis/
        batch_size: 256
        positive_only: false
        num_workers: 4
        num_samples: null
        concat_type: "gLM2"
trainer:
    max_epochs: 1
    deterministic: true
    logger:
        class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            save_dir: 'logs'
            offline: true
            project: gLM_PPI_XAI
            name: 'TASmania/mycobacterium_tuberculosis/gLM2'
            log_model: false
            prefix: 'cosine-fastCJ'
    enable_checkpointing: true
    callbacks:
      - class_path: gLM.callbacks.SetupWandB 
      - class_path: gLM.callbacks.OutputLoggingCallback
        init_args:
          class_names:
          - 'Negative'
          - 'Positive'
          y_pred_key: predictions
          y_pred_lab_key: predicted_label
          y_true_lab_key: label
          make_one_hot: true
          invert_probabilities: false
          make_correct_dim: true
          metrics_to_plot:
            - confusion_matrix
            - class_proportions
            - calibration_curves
            - classification_report
            - mcc
            - roc_auc
            - pr_auc
          log_every_n_steps: 1
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
            dirpath: logs/TASmania/mycobacterium_tuberculosis/gLM2/checkpoints/optimized/
            filename: model-{epoch}
            monitor: validate/loss
            mode: min
            save_last: true
            save_top_k: 1
