seed_everything: 42
model:
    class_path: gLM.models.gLM2
    init_args:
        model: 
            class_path: gLM.models.CategoricalJacobian
            init_args:
                fast: true
data:
  class_path: gLM.dataloader.SequencePairDataModule
  init_args:
    fasta_file: ../data/simple/sequences.fasta
    data_folder: ../data/simple/
    batch_size: 4096
    positive_only: false
    num_workers: 0
    num_samples: null

