seed_everything: 42
model:
  class_path: gLM.models.gLM2
  init_args:
    model:
      class_path: gLM.models.PredictorPPI
      init_args:
        emb_dim: 1280
        hid_size: 640
data:
  class_path: gLM.dataloader.EmbeddingsDataModule
  init_args:
    data_folder: ./data/JOB_PAR_NAME
    pt_folder: ./embeddings/JOB_PAR_NAME/REPRESENTATION/BIOLM_MODEL/
    batch_size: 16
    positive_only: false
    num_workers: 4
    num_samples: null
    concat_type: CONCAT
    kfolds: 5
    kfold_idx: 0
    seed: 42
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
    weight_decay: 0.01
    betas:
    - 0.9
    - 0.98
trainer:
  max_epochs: 100
  deterministic: true
  accumulate_grad_batches: 1
  log_every_n_steps: 1
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      save_dir: logs/gLM.models.PredictorPPI/JOB_PAR_NAME/REPRESENTATION/BIOLM/0/
      offline: true
      project: gLM_PPI_XAI
      name: JOB_PAR_NAME/REPRESENTATION/BIOLM/0/
      log_model: false
      prefix: 'CV'
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      patience: 5
      monitor: validate/loss
      mode: min
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: logs/gLM.models.PredictorPPI/JOB_PAR_NAME/REPRESENTATION/BIOLM/0/checkpoints/
      filename: model-{epoch}
      monitor: validate/loss
      mode: min
      save_last: true
      save_top_k: 1
  - class_path: gLM.callbacks.OutputLoggingCallback
    init_args:
      class_names:
      - Negative
      - Positive
      y_pred_key: predictions
      y_pred_lab_key: predicted_label
      y_true_lab_key: label
      make_one_hot: true
      invert_probabilities: false
      make_correct_dim: true
      metrics_to_plot:
      - confusion_matrix
      - class_proportions
      - calibration_curves
      - classification_report
      - mcc
      - roc_auc
      - pr_auc
      log_every_n_steps: 1
      metric_log_file: logs/gLM.models.PredictorPPI/JOB_PAR_NAME/REPRESENTATION/BIOLM/0/metrics.csv
