seed_everything: 42
model:
    class_path: gLM.models.gLM2
    init_args:
        model: 
            class_path: gLM.models.PredictorPPI
            init_args:
                emb_dim: 2560
                hid_size: 640
data:
    class_path: gLM.dataloader.EmbeddingsDataModule
    init_args:
        data_folder: /scicore/home/schwede/pudziu0000/projects/gLM/data/PINDER/eubacteria_5_1024_512_species_heterodimers/
        pt_folder: /scicore/home/schwede/pudziu0000/projects/gLM/embeddings/PINDER-eubacteria-species-heterodimers/gLM2_650M_3rd/
        batch_size: 128
        positive_only: false
        num_workers: 4
        num_samples: null
optimizer:
    class_path: torch.optim.Adam
    init_args:
        lr: 0.001
        weight_decay: 0.01
        betas:
        - 0.9
        - 0.98
trainer:
    max_epochs: 100
    deterministic: true
    logger:
        class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            save_dir: 'logs'
            offline: true
            project: gLM_PPI_XAI
            name: 'PINDER-eubacteria-sp-hetero-gLM2'
            log_model: false
            prefix: '3rd-pooled-emb'
    enable_checkpointing: true
    callbacks:
      - class_path: gLM.callbacks.SetupWandB
      - class_path: pytorch_lightning.callbacks.EarlyStopping
        init_args:
            patience: 5
            monitor: validate/loss
            mode: min
      - class_path: gLM.callbacks.OutputLoggingCallback
        init_args:
            log_every_n_steps: 1
      - class_path: gLM.callbacks.LogClassificationMetrics
        init_args:
          class_names:
          - 'Negative'
          - 'Positive'
          y_pred_key: predictions
          y_pred_lab_key: predicted_label
          y_true_lab_key: label
          make_one_hot: true
          invert_probabilities: false
          make_correct_dim: true
          metrics_to_plot:
            - confusion_matrix
            - class_proportions
            - calibration_curves
            - classification_report
            - mcc
            - roc_auc
            - pr_auc
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
            dirpath: logs/PINDER-eubacteria-species-heterodimers/gLM2_3rd/checkpoints/optimized/
            filename: best
            monitor: validate/loss
            mode: min
            save_last: false
            save_top_k: 1
