seed_everything: 42
model:
    class_path: gLM_CNN.models.PredictorPPI
    init_args:
        logits_model: 
            class_path: gLM_CNN.models.LogitsTensorGenerator
            init_args:
                model_path: "./gLM2_650M/"
                config_path: ""
                fast: true
                tensor_path: ./outputs/logits_tensors/glm2/
        model:
            class_path: gLM_CNN.models.LogitsTensorCNN
            init_args:
                tensor_dim: 1026
                num_in_channels: 48            
data:
    class_path: gLM_CNN.dataloader.UQRDataModule
    init_args:
        fasta_file: ./data/PINDER/eubacteria_5_1024_512_species_heterodimers/sequences.fasta
        data_folder: ./data/PINDER/eubacteria_5_1024_512_species_heterodimers/
        urq_folder: ./outputs/urqs/contact_maps/
        batch_size: 32
        positive_only: false
        num_workers: 4
        num_samples: null
        concat_type: "gLM2"
optimizer:
    class_path: torch.optim.Adam
    init_args:
        lr: 0.001
        weight_decay: 0.0001
trainer:
    max_epochs: 1000
    deterministic: true
    logger:
        class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
            save_dir: 'logs'
            offline: true
            project: gLM_PPI_XAI
            name: 'LogitsTensorsCNN'
            log_model: false
            prefix: 'gLM2'
    enable_checkpointing: true
    callbacks:
      - class_path: gLM.callbacks.SetupWandB 
      - class_path: gLM.callbacks.OutputLoggingCallback
        init_args:
            log_every_n_steps: 1
      - class_path: gLM.callbacks.LogClassificationMetrics
        init_args:
          class_names:
          - 'Negative'
          - 'Positive'
          y_pred_key: predictions
          y_pred_lab_key: predicted_label
          y_true_lab_key: label
          make_one_hot: true
          invert_probabilities: false
          make_correct_dim: true
          metrics_to_plot:
            - confusion_matrix
            - class_proportions
            - calibration_curves
            - classification_report
            - mcc
            - roc_auc
            - pr_auc
      - class_path: pytorch_lightning.callbacks.ModelCheckpoint
        init_args:
            dirpath: logs/LogitsTensorsCNN/gLM2/checkpoints/optimized/
            filename: model-{epoch}
            monitor: validate/loss
            mode: min
            save_last: true
            save_top_k: 1
